resolver 127.0.0.11 valid=30s;

server {
    listen 80;
    server_name medisonpatuakhali.com www.medisonpatuakhali.com localhost 72.60.204.20;

    # 1. React Frontend (SPA Routing)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 2. Django API Routes
    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 3. Django Admin Route
    location /medison_dashboard_management/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # 4. Django Static Files (CSS, JS)
    location /django_static/ {
        alias /app/staticfiles/;
    }

    # 5. Django Media Files (Images)
    location /media/ {
        alias /app/media/;
    }
}